apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: udacity-demo
spec:
  ingressClassName: nginx-example
  rules:
  - host: local.host
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          serviceName: loadbalancer-service
          servicePort: 8111