apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: udacity-demo
spec:
  ingressClassName: nginx-example
  rules:
  - host: local.host
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
              name: loadbalancer-service
              port:
                number: 8111