apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine-service
  namespace: udacity-demo
spec:
  ports:
  - protocol: TCP
    port: 8111
    targetPort: 80
  selector:
    app: nginx
    tag: alpine
  type: ClusterIP