apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    # path: exercises/manifests 
    # repoURL: https://github.com/udacity/nd064_course_1 
    path: argocd/manifests 
    repoURL: https://github.com/hosamelbasiony/python-helloworld-udacity
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}

  # kubectl apply -f https://github.com/hosamelbasiony/python-helloworld-udacity/argocd/nginx-alpine.yaml